# Generated by Django 4.0.3 on 2022-03-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_producent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.producent'),
        ),
    ]
