# Generated by Django 4.0.3 on 2022-03-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_kategoria_product_kategoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kategoria',
            new_name='Category',
        ),
    ]
