# Generated by Django 4.0.3 on 2022-03-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_rename_kategoria_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
